### ISSUE TITLE
这个软件可以检测拷贝数变异吗？

### ISSUE THREAD

**Issue by lqsae** [tjiangHIT/cuteSV#103]
hi, 姜博士
      你好， 之前用WES检测到了一个800k左右的 拷贝数变异， 我用三代的数据检测了该样本， 但是没检测到该变异， 通过查看IGV可以发现该区域存在拷贝数变异。 目前该款软件可以检测拷贝数变异吗？
![image](https://user-images.githubusercontent.com/40426930/196832838-1bf9d48e-6af6-4730-8bd8-64917d2d1f24.png)

**Comment by tjiangHIT** [comment]
你好，
感谢使用cuteSV，当前该软件可完成基于三代测序数据的插入、删除、重复、倒位、易位五种类型的结构变异检测任务。对于拷贝数变异，目前还不适用。

祝好，
姜涛
