### ISSUE TITLE
Modify the sequence of the inserted allele

### ISSUE THREAD

**Issue by zhqduan** [tjiangHIT/cuteSV#104]
Hi Tao,

In the v2.0.0, cuteSV modify the sequence of the inserted allele. So in the newest version, does the inserted allele become the consensus sequences from the supporting reads? If so, how the consensus sequences generate?
Thank you so much!

**Comment by Meltpinkg** [comment]
Hi,
In the newest version, the inserted allele is not from the consensus sequences from the supporting reads.

Best,
Shuqi

**Comment by zhqduan** [comment]
Thanks for your kind reply!

Best
Zhongqu
