### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/misha/Documents/Forsburg Lab/cuteSV/DEL.sigs'

### ISSUE THREAD

**Issue by mishakhm** [tjiangHIT/cuteSV#106]
Hi,
I just installed cuteSV and am trying to run it, but I get this error:
![image](https://user-images.githubusercontent.com/104739258/200942557-4c0e1821-7362-47e7-9833-99543e0938c8.png)
This also happens when running without extra arguments, as follows:
![image](https://user-images.githubusercontent.com/104739258/200942964-0c480bb6-2850-44ed-9283-2e193d61a85a.png)

I have tried multiple BAM and reference files and still get this error. Please let me know if I'm doing something wrong and how to resolve the problem. Thank you!

**Comment by Meltpinkg** [comment]
Hello, @mishakhm 

I think the error is caused by the vacancy of variation signatures in the BAM file, and we lack some handling on this event in cuteSV.
I have a further question. Can you have a look at the directory `/mnt/c/Users/misha/Documents/Forsburg Lab/cutesv/signatures` to see if there is any file in the directory? If is, what are the size of these documents?
It will be helpful for me to resolve the problem.
Thanks a lot!

Best,
Shuqi

**Comment by mishakhm** [comment]
Thanks, I see.
These files were created upon running cuteSV, before it errored out:
![image](https://user-images.githubusercontent.com/104739258/201194056-52558f4a-b82f-441c-bcdd-60811afb1b84.png)

**Comment by Meltpinkg** [comment]
Does your terminal has the commands of _sort_? cuteSV uses this command to generate SV signatures.
In other words, you can try the following commands in your terminal (in the signatures directory), and check whether it throws errors.
`cat *.bed | grep -w DEL | sort -u -T ./ | sort -k 2,2 -k 3,3n -T ./ | less`

**Comment by mishakhm** [comment]
Yes, that command works fine and displays the following output:
![image](https://user-images.githubusercontent.com/104739258/201797159-33895b35-09c0-4a4d-988f-68892f68a29a.png)
After exiting the view, no errors are shown:
![image](https://user-images.githubusercontent.com/104739258/201797221-55892782-2f6c-491a-aac1-412e4256e13f.png)
It's an Ubuntu 20.04 shell, though it is running through Windows Subsystem for Linux so there's a slight chance that could be causing the problem? In theory it shouldn't, as it's a full Linux kernel. Thanks for your help so far!

**Comment by mishakhm** [comment]
Sure, I just emailed you the files.
I was using cuteSV version 2.0.2 and Python 3.8.10.

**Comment by Meltpinkg** [comment]
I applied cuteSV 2.0.2 on the provided data with the following commands.
`cuteSV Iso1_Ch1_Bam.bam /data/1/sqcao/ref/hs37d5.fa output.vcf ./ --retain_work_dir`
It did not throw error and finished successfully.
![image](https://user-images.githubusercontent.com/47966870/202152523-4a2b36ef-4928-47fc-89e5-21eff338e878.png)
Also, the sigs file were generated.
![image](https://user-images.githubusercontent.com/47966870/202154027-f50fd3ac-e643-4ec1-b8f8-52586315fc53.png)

I think maybe something in your environment influenced the running of cuteSV. You can try create a new environment and run cuteSV with the corresponding dependence, and check whether the .sigs file can be generated.

**Comment by mishakhm** [comment]
I tried to set up a fresh install of Ubuntu and reinstalled cuteSV, but initially still got the error. However, changing my working directory argument from passing in the full path of the current folder to your ./ --retain_work_dir caused it to run successfully:
![image](https://user-images.githubusercontent.com/104739258/202285013-f51a5465-af24-4817-9c1d-adaaba4f5eca.png)
Just out of curiosity, I tried adding --retain_work_dir to my previous command (passing in the full path) and this also caused an error. I tried both with and without an ending / on my path.
![image](https://user-images.githubusercontent.com/104739258/202288194-007558f3-86c8-4d3f-967d-e82ca6f5f1cf.png)
Anyways, I'm glad I got it to work using ./. I'm a little confused why it didn't work with manually passing in the path, as my impression is that ./ should be the same as passing in the full path of the current folder, but maybe I'm wrong. Thanks for all your help!

**Comment by Meltpinkg** [comment]
@mishakhm I'm glad to hear your success! cuteSV parses the given directory and writes temporary files into it. Maybe you can try to remote the quotation: **"** from the directory in the commands? I'm not sure whether the quotation causes the failure in parsing the directory path.
