### ISSUE TITLE
What's the recommended parameters for assembly-level alignment SV calling 

### ISSUE THREAD

**Issue by luckyvivi** [tjiangHIT/cuteSV#107]
Dear Dr. Jiang,
Thanks for develop such a good tools, I'm currently using cuteSV 2.0.2.
As for PacBio CLR data, CCS(HIFI) data and ONT data already have suggested parameters, I'm curious about what's the proper parameters for genome assembly-level alignment SV calling. 

Best,
Xiaowen

**Comment by tjiangHIT** [comment]
Hello @luckyvivi,

Thanks for using cuteSV.
To help users apply cuteSV to perform genome assembly-level alignment SV calling, we give a wiki page to describe it [here](https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV).
This page contains a demo case and the corresponding benchmark results.
Hope this can help you.

Best regards,
Tao
