### ISSUE TITLE
query about missing genotypes in cuteSV force calling

### ISSUE THREAD

**Issue by prasundutta87** [tjiangHIT/cuteSV#108]
Hi,

When we call SVs using force calling in a trio, there are cases where there is  `./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN ` in either one parent or both the parents. However there is an SV called (DEL) in the child. Should I treat it as a de novo variant (where both parents have missing genotype)? I guess no SVs were called in parents as there were no reads there. Am I correct in interpreting this?

Regards,
Prasun

**Comment by Meltpinkg** [comment]
Hi, @prasundutta87 

In this condition, there is large probability that it is a de novo variant in child. However, considering the error-prone sequencing and noises in the data processing, we highly recommend to check the IGV screenshot to ensure the missing genotype of parents and existence of the variant of child. With the proof of IGV, the de novo variant will be more convincing.

Best regards,
Shuqi
