### ISSUE TITLE
events don't merge with svanalyzer

### ISSUE THREAD

**Issue by proinde** [tjiangHIT/cuteSV#11]
I have been using svanalyzer with sniffles calls to compare SVs between members of a family of individuals, and while sniffles calls merge when they have an ALT allele sequence or are both in cis and defined by a pair of points (e.g. deletions with a start and stop coordinate delineating the entire event), my cuteSV calls do not merge between samples at all, despite, in some cases, of being clearly the same SV inherited from parent to child.

**Comment by tjiangHIT** [comment]
Hello @proinde 

Now cuteSV can report deleted sequence in ALT filed. Please git clone the latest version and check whether this update can solve your problem.
As for reporting inserted sequence in ALT field (also see #10 and #8 ), I am trying to find a way to beat it.
Look forward to your reply.

Tao
