### ISSUE TITLE
Length of the output of SVs

### ISSUE THREAD

**Issue by jyw-atgithub** [tjiangHIT/cuteSV#113]
Hi, 
I am calling SVs from _Drospphila melanogaster_ with Nanopore sequences. I set the minimal length of SV as 50 (_-l 50_). But when I viewed the VCF file, it reported any SVs longer than 10bp. May I know how to fix it? The commands and partial results are attached. Thank you! 
Best, 

Jen-Yu

__1.  commands__

```bash
cuteSV --threads 20 --genotype \
-l 50 -L 500000 \
-r 500 -q 20 -s 3 \
--max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 100 --diff_ratio_merging_DEL 0.3 \
--sample ${name} \
$j ${ref_genome} "${name}-cutesv.vcf" .
```

__2. result vcf__  I used "SVLEN" as the length of the length of SV.

```
2L      149767  cuteSV.DEL.1003 GCCAGCGTCTTCAT  G       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-13;END=149780;CIPOS=-26,26;CILEN=-2,2;RE=5;RNAMES=NULL;AF>
2L      150167  cuteSV.DEL.1004 GTTTATAAGTTTT   G       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-12;END=150179;CIPOS=-43,43;CILEN=-2,2;RE=4;RNAMES=NULL;AF>
2L      150450  cuteSV.DEL.1005 CGTTAAAATTTAC   C       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-12;END=150462;CIPOS=-38,38;CILEN=-2,2;RE=3;RNAMES=NULL;AF>
2L      150742  cuteSV.DEL.1006 GTGCTCGCTTAT    G       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-11;END=150753;CIPOS=-78,78;CILEN=-0,0;RE=4;RNAMES=NULL;AF>
2L      151218  cuteSV.DEL.1007 GTTCGACTAATA    G       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-11;END=151229;CIPOS=-51,51;CILEN=-1,1;RE=5;RNAMES=NULL;AF>
2L      152093  cuteSV.DEL.1008 TCCCATGTCCAAGCAG        T       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-15;END=152108;CIPOS=-93,93;CILEN=-3,3;RE=9;RNAMES>
2L      152609  cuteSV.DEL.1009 GAGAGCTCCTTT    G       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-11;END=152620;CIPOS=-53,53;CILEN=-0,0;RE=11;RNAMES=NULL;A>
2L      153226  cuteSV.DEL.1010 CTCGGTCACTT     C       0       q5      IMPRECISE;SVTYPE=DEL;SVLEN=-10;END=153236;CIPOS=-47,47;CILEN=-0,0;RE=5;RNAMES=NULL;AF>
2
```

__3. I used bcftools query and R to organize the lengths__

![image](https://user-images.githubusercontent.com/53656868/227462335-c5a0ce52-cf96-4eea-9b93-cf4eec67c0ff.png)

**Comment by tjiangHIT** [comment]
Hello @jyw-atgithub,

Sorry for replying too late.
Could you provide a small bam file covering some cases like these for us in order to reproduce the issue and debug it?
I will appreciate it if you can supply it. My email is tjiangAThitDOTeduDOTcn.

Best,
Tao

**Comment by tjiangHIT** [comment]
Hello @jyw-atgithub,
Please follow issue #110  to solve this.
Best wishes,
Tao

**Comment by jyw-atgithub** [comment]
Hi @tjiangHIT , 
Thank you for providing the solution. I tried to reinstall the program, but encountered an error. 
My command was `python3 setup.py install --user` 
The following is part of the output. Thank you again.

```
Downloading https://files.pythonhosted.org/packages/20/b6/36bfb1760f6983788d916096193fc14c83cce512c7787c93380e09458c09/PyVCF-0.6.8.tar.gz#sha256=e9d872513d179d229ab61da47a33f42726e9613784d1cb2bac3f8e2642f6f9d9
Best match: PyVCF 0.6.8
Processing PyVCF-0.6.8.tar.gz
Writing /tmp/easy_install-lpl0dtpr/PyVCF-0.6.8/setup.cfg
Running PyVCF-0.6.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lpl0dtpr/PyVCF-0.6.8/egg-dist-tmp-qs5vy87_
error: Setup script exited with error in PyVCF setup command: use_2to3 is invalid.
```

**Environment**

OS: Ubuntu 22.04.2 LTS
Python 2.7.18
Python 3.10.6

**Comment by tjiangHIT** [comment]
Hello @jyw-atgithub,
Please follow issue #116 to solve this.
Best wishes,
Tao

**Comment by jyw-atgithub** [comment]
Hi @tjiangHIT , 
Thank you very much! cuteSV is installed successfully.

**Comment by tjiangHIT** [comment]
Hello @jyw-atgithub,

Glad to hear this good news.
Is this problem solved through the version of codes in our GitHub?
Feel free to contact us.

Best regards,
Tao
