### ISSUE TITLE
 R package

### ISSUE THREAD

**Issue by huangrongbioinfomation** [tjiangHIT/cuteSV#117]
What R package was used to draw the graph?
![image](https://user-images.githubusercontent.com/54733697/237020921-940f07ea-31a5-4b6a-8658-490f3e83cab7.png)

**Comment by tjiangHIT** [comment]
We just used PowerPoint to draw this figure.

**Comment by huangrongbioinfomation** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到邮件
