### ISSUE TITLE
work_dir parameter error

### ISSUE THREAD

**Issue by ViriatoII** [tjiangHIT/cuteSV#12]
Hey,

your program looks very interesting but I can't run. What's does the work_dir parameter mean??  If I omit it, I get an error

```
2020-09-03 16:45:01,175 [INFO] Running /home/guerrer/.local/bin/cuteSV mapped_sorted.bam ref.fasta mapped.vcf  --max_cluster_bias_INS 1000 --threads 12 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5
2020-09-03 16:45:01,198 [INFO] The total number of chromsomes: 267
Traceback (most recent call last):
  File "/home/guerrer/.local/bin/cuteSV", line 708, in <module>
    run(sys.argv[1:])
  File "/home/guerrer/.local/bin/cuteSV", line 704, in run
    main_ctrl(args, argv)
  File "/home/guerrer/.local/bin/cuteSV", line 562, in main_ctrl
    os.mkdir("%ssignatures"%temporary_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'mapped.vcf/signatures'
```

if I try to put a directory, it's not recognized:

cuteSV mapped_sorted.bam ref.fasta mapped.vcf  ../folder_where_I_am

`cuteSV: error: unrecognized arguments: ../folder_where_I_am
`

Cheers,
Ricardo

**Comment by tjiangHIT** [comment]
Hello @ViriatoII 

Thanks for using cuteSV and pointing this issue.
Please give a real existence folder (like ./) enable cuteSV to produce temporary files and finish SV calling.
After detection, cuteSV will remove all the temporary files in that folder. If you want to save them, please use --retain_work_dir.

Best,
Tao

**Comment by ViriatoII** [comment]
Hi @tjiangHIT ,

Thank you for the fast reply, I still have the same problem:

`                cuteSV mapped_sorted.bam  ref.fasta  mapped.vcf   "./"  
                --max_cluster_bias_INS 1000  --threads 12  
                --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL     1000 
                --diff_ratio_merging_DEL 0.5
`

cuteSV: error: unrecognized arguments: ./

(also happens if "./" is out of quotations)

**Comment by ViriatoII** [comment]
Ok, I see now. I was putting one parameter too much, the output_name "mapped.vcf". 

That's what your page indicates, but the program does not like it?

> cuteSV <sorted.bam> <reference.fa> <output.vcf> <work_dir>

**Comment by tjiangHIT** [comment]
Hello @ViriatoII 

Yes, the older versions (<=1.0.6)  just use _cuteSV <sorted.bam> <output.vcf> <work_dir>_  to perform SV calling.
The latest versions (>=1.0.7) support the generation of allele sequences. and need to use  _cuteSV <sorted.bam> <reference.fa> <output.vcf> <work_dir>_.
Please check the version of your cuteSV.
Best,
Tao

**Comment by ViriatoII** [comment]
Thank you for the help. I was indeed working with 1.0.7, installed from pip.

**Comment by tjiangHIT** [comment]
Hello @ViriatoII 
I strongly recommend that clone my latest code form my GitHub by git.
The current version of cuteSV in PyPI is out of date.
Best,
Tao

**Comment by wdecoster** [comment]
Wouldn't it be more elegant if either the software creates non-existing working directories or gives a better error message that the directory doesn't exist?
I just came across `FileNotFoundError: [Errno 2] No such file or directory: 'cutesv-temp/signatures'` myself, and it's rather cryptic what is wrong.

**Comment by tjiangHIT** [comment]
Hello @wdecoster 
Thanks for the suggestion. 
Indeed, some of the descriptions of errors do not seem appropriate, and I'll improve on that later.
Best,
Tao
