### ISSUE TITLE
Confusing read support for a large deletion

### ISSUE THREAD

**Issue by wongkarenhy-hex** [tjiangHIT/cuteSV#126]
Thanks for providing such a great SV calling tool! I recently encountered a perplexing case involving a large deletion that only had three read supports, while there should have been at least several dozen. The data was generated from ONT.

Based on the IGV screenshot, I was expecting to see a high confidence deletion call at 302-14768. 

Initially I used the recommended settings for ONT but it failed to identify the deletion call. I then modified the command as follows:
`cuteSV --max_cluster_bias_INS 10 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 100 --diff_ratio_merging_DEL 0.3 --min_read_len 200 --max_split_parts 5 --min_support 2 test.sorted.bam ref.fasta test_cuteSV.vcf /tmp`

The resulting vcf did show the expected deletion call at position 303 but the RE is only 3. 

Additional context: this is actually a circular plasmid so there are overlapping DUP calls spanning the entire contig. I'm happy to share files via email as well.

<img width="1256" alt="image" src="https://github.com/tjiangHIT/cuteSV/assets/93940009/6c4e517f-e2cf-4622-8d42-1adca42a7f4c">

**Comment by tjiangHIT** [comment]
Hello @wongkarenhy-hex,

Thanks for pointing out this case.
I would be pleased if you could share the ref.fa and bam files.
My email is tjiang@hit.edu.cn.

Best regards,
Tao

**Comment by Meltpinkg** [comment]
Hello, @wongkarenhy-hex 

Thanks for providing the test datasets.
The confusing read support came from the incomplete regulations in handling variation signatures in the old version. We have improved the regulations in the new version (v2.0.3). You can install the newest version from GitHub via the following commands.
```
git clone https://github.com/tjiangHIT/cuteSV.git && cd cuteSV/ && python setup.py install
```

Hope it will help.

Best,
Shuqi

**Comment by wongkarenhy-hex** [comment]
Thanks for promptly addressing this! I would like to confirm that the new version did find the expected call.
