### ISSUE TITLE
Supporting gzip ref fasta

### ISSUE THREAD

**Issue by baozg** [tjiangHIT/cuteSV#128]
Hi, @tjiangHIT 

Would be possible to support the bgzipped reference fasta? Now, the `cuteSV` only accepts plain reference.

**Comment by Meltpinkg** [comment]
Hello, @baozg 

We have updated a new version in GitHub that supports the bgzipped reference fasta. You can install the newest version from GitHub through the following commands, and the other installation ways (pip and conda) will be updated later.
```
git clone https://github.com/tjiangHIT/cuteSV.git && cd cuteSV/ && python setup.py install
```

Best,
Shuqi

**Comment by baozg** [comment]
Thanks!
