### ISSUE TITLE
`--min_size` didn't work

### ISSUE THREAD

**Issue by baozg** [tjiangHIT/cuteSV#130]
Hi, 

Even if I set the `--min_size 50`, the output SVs still include short SVs. Here is the command I use:

```bash
cuteSV --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5 results/01.mapping/11C1.sorted.bam ref/Col-CC.fa 11C1.cutesv.vcf 11C1_test --min_mapq 20 --sample 11C1 --threads 12 --min_size 50 --genotype
```

**Comment by CoREse** [comment]
Hello, @baozg

This has been fixed, see [issue 110](https://github.com/tjiangHIT/cuteSV/issues/110) for details.

Best regards,
CRE
