### ISSUE TITLE
[Question] How are POS, LEN and SEQ of insertions determined

### ISSUE THREAD

**Issue by waltergallegog** [tjiangHIT/cuteSV#131]
Dear developer,
I would like to understand how cuteSV currently determines the Position, length and sequence of an insertion, specially when there is a lot of variance in the reads. For example in the insertion in the image, there are 29 supporting reads, with insertion length ranging from 166 to 343.

The insertion is called by cutesv with length 253.

From my understanding by reading https://github.com/tjiangHIT/cuteSV/issues/66 and https://github.com/tjiangHIT/cuteSV/pull/73, the len pos and sequence reported by cutesv is taken from one of the reads, that satisfies a certain criteria. However, looking at the 29 reads in that location, I can not find a read whose length is 253.

 - Is my understanding correct? 
 - Is there any way to understand from the vcf which of the reads was selected as the representative of the insertion? (For example the first read reported in the  RNAMES field)
 - Has cutesv been updated to calculate the len pos and sequence in a different way?

![image](https://github.com/tjiangHIT/cuteSV/assets/5270762/62ab7e78-d1af-490c-9e7e-2d3807c9d421)

Thank you very much for your support.

**Comment by CoREse** [comment]
Hello, @waltergallegog

As depicted in the generate_ins_cluster function in the cuteSV_resolveINDEL.py, the length is determined as the mean length of the insertion signatures, while the position, as well as the insertion sequence, is determined by those of the first encountered insertion signature that has the length no shorter than the mean length.

As for the second question, the RNAMEs filed won't show the read that was used to determine the insertion sequence.

Best regards,
CRE

**Comment by waltergallegog** [comment]
Thanks for the information.
BR
Walter
