### ISSUE TITLE
SV with genotype 0/0

### ISSUE THREAD

**Issue by vegetableyu** [tjiangHIT/cuteSV#137]
Hi，
I wonder how to interpret SV as genotype 0/0. If genotype 0/0 doesn't that mean there is no variation here?
All the best,
YU

**Comment by Meltpinkg** [comment]
Hello, @vegetableyu 

When there were corresponding SV signatures on the sequencing reads, the SV was reported. In this condition, if the coverage of the SV alleles didn't support it as a homozygous or heterozygous variation, it will be genotyped as 0/0.

Best,
Shuqi
