### ISSUE TITLE
empty pickle for self mapping

### ISSUE THREAD

**Issue by baozg** [tjiangHIT/cuteSV#138]
Hi, @tjiangHIT 

If I used `cuteSV` to validate the genome assembly error (HiFi reads mapping back to the assembly itself). Some pickles will be empty, but `cuteSV` will report errors to these regions although the output looks fine.

```bash
Traceback (most recent call last):
  File "/ebio/abt6_projects7/conda/env/bin/cuteSV", line 1267, in <module>
    run(sys.argv[1:])
  File "/ebio/abt6_projects7/conda/env/bin/cuteSV", line 1263, in run
    main_ctrl(args, argv)
  File "/ebio/abt6_projects7/conda/env/bin/cuteSV", line 1230, in main_ctrl
    with open("%sresults/%s.pickle"%(temporary_dir,chrom), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './LACR-C-4_tmp/results/Chr5.pickle'
```

**Comment by Meltpinkg** [comment]
Hello, @baozg 

Sorry for my late reply. This has been fixed in the newest version. Please git clone cuteSV via GitHub and install it.
Hope it will help.

Best,
Shuqi
