### ISSUE TITLE
cutcsv only calls indel

### ISSUE THREAD

**Issue by HFzzzzzzz** [tjiangHIT/cuteSV#141]
Why do I use cutcsv to call vcf on my bam file, but I can only get very few vcfs, and they are all indels. In igv, it is clear that there are many small mutations.
![image](https://github.com/tjiangHIT/cuteSV/assets/50006357/423d8ea6-ec5b-4937-a3ee-9db8abbbd714)   
I used command ' cuteSV aln.end.bam  Col-CEN_v1.2.fasta  ERR3415821_col-0.cutesv.vcf  workdir3'
 https://drive.google.com/file/d/1S7Q8ol-XXVCyHowBg9IzMOznVZXF39Ul/view?usp=drive_link
https://drive.google.com/file/d/1RYtp84hlx8p4ZYqPdXvwUPMWk67Zhb_J/view?usp=drive_link
Can you help me find out what the problem is? Is there something wrong with the bam file?

**Comment by tjiangHIT** [comment]
Hello @HFzzzzzzz,

Thank you for using cuteSV.
Based on your description, the coverage of your aln.end.bam may be too small. Please adjust the parameter -s to above 1/6 of your coverage to increase the detection sensitivity. Besides, cuteSV focuses on identifying SVs over 30 bp at least. 
Hope this can help you!
Best,
Tao
