### ISSUE TITLE
zero position in vcf

### ISSUE THREAD

**Issue by baozg** [tjiangHIT/cuteSV#147]
Hi, 

VCF should be 1-based coordinate system, why `cuteSV` report postion as 0 in the telomere region?

**Comment by Meltpinkg** [comment]
Hello, @baozg 

According to VCF format (v4.2), the position field is indicated as: `Telomeres are indicated by using positions 0 or N+1, where N is the length of the corresponding chromosome or contig.` Thus the position 0 represents the SV happened in the telomere region.
Hope it will help!

Best,
Shuqi

**Comment by baozg** [comment]
Thanks. Did `cuteSV` will try to find TxAyGz repeat? `bcftools` will output warning for this location and it cannot put in a bed format, since it use 0-based format

**Comment by Meltpinkg** [comment]
Hello, @baozg 
We haven't try to find TxAyGz repeat. To use `bcftools` in this condition, you can make some post-processing on this vcf to avoid the warnings. I'd like to mention that the position given by cuteSV (version >= 2.0) is 1-based actually.

**Comment by baozg** [comment]
Thanks anyway. I will filter these variants by myself
