### ISSUE TITLE
Does cuteSV only call the inter-chromosome translocation?

### ISSUE THREAD

**Issue by hui-liu** [tjiangHIT/cuteSV#149]
Hi,

I found the VCF file only contained the translocation from different chromosomes. Did cuteSV not call the translocation within a chromosome?

**Comment by Meltpinkg** [comment]
Hi, @hui-liu 

Yes, cuteSV now only detected the translocation from different chromosomes; the translocation within a chromosome is not included.

Best,
Shuqi
