### ISSUE TITLE
Failed to benchmark on truvari

### ISSUE THREAD

**Issue by lok27395** [tjiangHIT/cuteSV#155]
Dear author,

I am using cuteSV to call SV on HG002 aligned bam CHM13. The output vcf cannot be used for truvari bench. Error: no TP or FP calls in comp.

Other SV caller are able to be benchmarked using this bam.

> (https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_HiFi-Revio_20231031/)

cuteSV used: 2.1.1; truvari used: 4.3.1 (all setting are defaults nothing modified)

Please advice. Thank you!

**Comment by CoREse** [comment]
Hi lok,

Can you post your exact run command for cuteSV?

Bests,
CRE

**Comment by CoREse** [comment]
Hi lok,

Can you post your exact run command for cuteSV?

Bests,
CRE

**Comment by lok27395** [comment]
`cuteSV HG002_PacBio-HiFi-Revio_20231031_48x_CHM13v2.0.bam ~/human_ref/chm13v2.0.fa cutesv_48X.vcf --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5 ~/HG002_call`
[cutesv_48X.vcf.gz](https://github.com/user-attachments/files/17290671/cutesv_48X.vcf.gz)

Truvari's command (according to https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.018-20240716/NIST_HG002_DraftBenchmark_defrabbV0.018-20240716_README_update.md)

> truvari bench \
    -b <benchmark variants vcf> \
    -c <comparison vcf> \
    -o <output dir> \
    --pick ac \
    --passonly \
    -r 2000 \
    -C 5000 \
    -f <reference fasta> \
    --includebed <benchmark regions bed>

> vcf and bed from: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.018-20240716/

**Comment by lok27395** [comment]
problem solved thx
