### ISSUE TITLE
QUAL value is equal to 0

### ISSUE THREAD

**Issue by DayTimeMouse** [tjiangHIT/cuteSV#157]
Hi,

I saw some QUAL values are equal to 0, even the FILTER is PASS. Should I set a cut-off to filter variants? Could you give me some sugestions for cut-off value?

Best regards.

**Comment by Meltpinkg** [comment]
Hello, @DayTimeMouse 

The QUAL values are calculated only when the _--genotype_ parameter is given. And by default, cuteSV filters the variants with QUAL values < 5. In my mind, after enabling _--genotype_, if the QUAL values equal to 0, it will be marked as _q5_, not _PASS_, and should be filtered. You can first confirm the commands in this way.
If there is any problem, please feel free to let me know.

Best regards.

**Comment by DayTimeMouse** [comment]
Yes, you are right, the FILTER column is q5. Thanks to response.
