### ISSUE TITLE
END smaller than POS

### ISSUE THREAD

**Issue by wdecoster** [tjiangHIT/cuteSV#17]
Hi,

I noticed for quite some interchromosomal BND variants the END is smaller than the POS, which results in problems with bcftools and tabix.
In fact, it is against the [VCF specifications](https://samtools.github.io/hts-specs/VCFv4.3.pdf) which define the END value as `End position on CHROM (used with symbolic alleles; see below)`

In more detail:
```
• END: End reference position (1-based), indicating the variant spans positions POS–END on reference/contig CHROM. Normally this is the position of the last base in the REF allele, so it can be derived from POS and the length of REF, and no END INFO field is needed. However when symbolic alleles are used, e.g. in gVCF or structural variants, an explicit END INFO field provides variant span information that is otherwise unknown. This field is used to compute BCF’s rlen field (see 6.3.1) and is important when indexing VCF/BCF files to enable random access and querying by position.
```

So it turns out the END field contains the end position on the same chromosome as in CHROM, and not on the other chromosome for interchromosomal variants.

Cheers,
Wouter

**Comment by tjiangHIT** [comment]
Hello @wdecoster 
Thank you so much for pointing this out.
Now I have removed the CHR2 and its END in the INFO filed, please check it.

Best,
Tao

**Comment by wdecoster** [comment]
That appears to work!
