### ISSUE TITLE
Problems about VISOR in simulated alignments generation

### ISSUE THREAD

**Issue by azure-twilight** [tjiangHIT/cuteSV#21]
cuteSV/simulate/README.md gives the way for simulated alignments gemeration, and I run this command:
VISOR LASeR -g reference_genome.fasta -s donor_genome_del -bed LASeR.bed -o data_del_5x -c 5 --threads 16 --noaddtag
when it finished it give me 3 files in data_del_5x,  sim.srt.bam、sim.srt.bam.bai and VISOR_LASeR.log
Then I run cuteSV with sim.srt.bam, the command like this:
cuteSV sim.srt.bam ref.fasta cutesv.vcf ./
but got the error:
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
It seems that there is something wrong in the .bam file, but I have no idea about it. Is there anyone could help me about this?

**Comment by tjiangHIT** [comment]
Hello @azure-twilight,

Thanks for using cuteSV.

cuteSV applied pysam library to load BAM file, and the error you got was raised by pysam (more precisely raised by pysam.AlignmentFile function). The error indicated that the bam files you generated was not fine. Please use samtools view to have a look into your file and check whether it is correct. Also, please review the VISOR_LASeR.log file to check your VISOR running correctly.

Best,
Tao

**Comment by jane13-cs** [comment]
Hello @tjiangHIT , @davidebolo1993 ,
I also found the same problem. I used "VISOR LASeR -g reference_genome.fasta -s donor_genome_del -bed LASeR.bed -o data_del_5x -c 5 --threads 16 --noaddtag" to get the same data, and then tried to run sim.srt.bam with SVIM or cuteSV, got the same error.
The data is stored at: https://pan.baidu.com/s/1gH5W1IUxHCeqqEjF9QupfA Password: 8er1
Can you help me check if there is any problem?

Thanks!

**Comment by davidebolo1993** [comment]
Hi everyone,

@jane13-cs, can you please provide the BAM and LOG using Dropbox. It seems I have to register in baidu to get the data. My email is davidebolognini7@gmail.com. 
Also, I'm working on a new VISOR version. If there is an issue, it's good to know so that I can fix this in the upcoming release.

Thanks,

Davide

**Comment by tjiangHIT** [comment]
Hello @azure-twilight and @jane13-cs,

I have checked the files supplied by @jane13-cs and find there is no available read alignments in it.
Please check your VISOR has been installed correctly (including the depended libraries like samtools, pbsim, minimap2, pybedtools, pysam and pyfaidx).

Tao

**Comment by davidebolo1993** [comment]
Hi @tjiangHIT,

as from their other comment (https://github.com/tjiangHIT/cuteSV/issues/20#issuecomment-740512963), it seems that all is solved (old samtools version was my guess). I think you can close this.

Best,

Davide

**Comment by jane13-cs** [comment]
Hello @tjiangHIT , @davidebolo1993 ,

After I deleted VISOR and reinstalled VISOR, the simulation data can be generated normally.
Now I have encountered a new problem. After the SV call on the simulated data, the evaluation result is very strange.

**Comment by tjiangHIT** [comment]
> Hi @tjiangHIT,
> 
> as from their other comment ([#20 (comment)](https://github.com/tjiangHIT/cuteSV/issues/20#issuecomment-740512963)), it seems that all is solved (old samtools version was my guess). I think you can close this.
> 
> Best,
> 
> Davide

Thank you for your reminder.

Tao

**Comment by tjiangHIT** [comment]
> Hello @tjiangHIT , @davidebolo1993 ,
> 
> After I deleted VISOR and reinstalled VISOR, the simulation data can be generated normally.
> Now I have encountered a new problem. After the SV call on the simulated data, the evaluation result is very strange.

Please go to the comment #20 for detailed reply.

Tao
