### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by mike-molnar** [tjiangHIT/cuteSV#23]
Hi,

Would it be possible to output the variants in BEDPE format with the number of supporting reads included in the output?  I would like to do some post variant call filtering with bedtools so I need to convert the VCF to BEDPE.  I currently am using SURVIVOR vcftobed to convert the VCF, but the output does not include the number of supporting reads for each call, which is part of the post filtering process.

Thanks,
Mike

**Comment by tjiangHIT** [comment]
Hello @mike-molnar,

Thanks for using cuteSV in your work.
For converting VCF file to BEDPE file, please use the script called [vcftobedpe.py](https://github.com/hall-lab/svtools/blob/master/svtools/vcftobedpe.py) in [svtools](https://github.com/hall-lab/svtools) which will help to finish this conversion and supply the complete messages (including read support) of INFO stored in VCF file.
Hope this help.

Best,
Tao

**Comment by mike-molnar** [comment]
Hi Tao,

Thanks for the quick reply.  I have tried using svtools for the conversion, but there are a few problems I have with it:

1.  svtools requires python 2.7, and I (like most people) have switched to at least python 3.6.
2.  I would prefer not to have a separate environment just to run svtools.  I have posted an issue with svtools about upgrading, but there have not been any replies to issues since May.  So it seems that this package is no longer being actively maintained.
3.  The output from the conversion is quite messy, and would require additional parsing to get to the information I need.  The output from SURVIVOR vcftobed is exactly what I am looking for, except that it does not output the support for the calls.  Sniffles outputs the proper format, which is a standard BEDPE format.  The output from svtools vcftobedpe is more like a VCF file.

I think it would be a good idea to have cuteSV output either VCF or BEDPE, similar to what Sniffles has done.  BEDPE is much easier to use for filtering calls with bedtools.

Mike

**Comment by tjiangHIT** [comment]
Hello @mike-molnar,

I develop a format conversion script named [vcf2bedpe.py](https://github.com/tjiangHIT/cuteSV/blob/master/src/benchmarks/vcf2bedpe.py) based on python3, which can help to convert the vcf file generated from cuteSV to bedpe file. Please run command like:
> python3 vcf2bedpe.py cuteSV.vcf cuteSV.bed

In the output bedpe file, the last column indicates the number of support read for the current SV.
If you have trouble in performing this script please keep me informed.

Best,
Tao

**Comment by mike-molnar** [comment]
That's great!  I tried it out and looks perfect.  Once again, thanks for the quick reply and resolution.

Cheers,
Mike
