### ISSUE TITLE
Add a wiki for SV calling based on diploid assembly alignment

### ISSUE THREAD

**Issue by tjiangHIT** [tjiangHIT/cuteSV#28]
Hello everyone,

A new script that post-processes the typically cuteSV callsets from assembly alignments has been developed. 
This will help users to generate the diploid-assembly-based SV callsets. 
The evaluations are shown that the F1 scores of SVs presence and genotype achieved over 95%.
More details please see [wiki](https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV).

Best,
Tao

**Comment by yekaizhou** [comment]
Hi,

Thank you very much for this update.

I am wondering if the diploid-called `HG002_final.vcf` is still benchmarked using `truvari` against the standard tier1 SV callset from GIAB? This callset seems not containing haplotype information.

Can you kindly provide the benchmarking code/design after `diploid_calling.py` gets the `HG002_final.vcf` result?

Thank you very much!

**Comment by tjiangHIT** [comment]
Hello @yekaizhou,

The evaluation of the diploid-called HG002_final.vcf is still applied truvari with the standard tier1 SV callset from GIAB.
More detailed scripts are as below:
```sh
less HG002_final.vcf | sed 's/1\/0/0\/1/g' | bgzip -c > HG002_final.vcf.gz 
tabix HG002_final.vcf.gz
truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz \
              -c HG002_final.vcf.gz \
              -o test -f hs37d5.fa \
              --giabreport -r 1000 -p 0 --passonly \
              --includebed HG002_SVs_Tier1_v0.6.bed
```
Hope this helps!
Best,
Tao

**Comment by yekaizhou** [comment]
> Hello @yekaizhou,
> 
> The evaluation of the diploid-called HG002_final.vcf is still applied truvari with the standard tier1 SV callset from GIAB.
> More detailed scripts are as below:
> 
> ```shell
> less HG002_final.vcf | sed 's/1\/0/0\/1/g' | bgzip -c > HG002_final.vcf.gz 
> tabix HG002_final.vcf.gz
> truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz \
>               -c HG002_final.vcf.gz \
>               -o test -f hs37d5.fa \
>               --giabreport -r 1000 -p 0 --passonly \
>               --includebed HG002_SVs_Tier1_v0.6.bed
> ```
> 
> Hope this helps!
> Best,
> Tao

Thanks a lot Tao! So `diploid_calling.py` is essentially doing genotyping from haplotype-resolved assemblies, rather than phasing, right?

**Comment by yekaizhou** [comment]
> Hello @yekaizhou,
> 
> The evaluation of the diploid-called HG002_final.vcf is still applied truvari with the standard tier1 SV callset from GIAB.
> More detailed scripts are as below:
> 
> ```shell
> less HG002_final.vcf | sed 's/1\/0/0\/1/g' | bgzip -c > HG002_final.vcf.gz 
> tabix HG002_final.vcf.gz
> truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz \
>               -c HG002_final.vcf.gz \
>               -o test -f hs37d5.fa \
>               --giabreport -r 1000 -p 0 --passonly \
>               --includebed HG002_SVs_Tier1_v0.6.bed
> ```
> 
> Hope this helps!
> Best,
> Tao

Thank you Tao! So basically, `diploid_calling.py` is generating haplotypical information, while the final evaluation by `truvari` is based on genotype level?

**Comment by tjiangHIT** [comment]
Yeah! @yekaizhou.
