### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'merge_del_threshold'

### ISSUE THREAD

**Issue by woodoo46** [tjiangHIT/cuteSV#3]
Hi there,

I ran cuteSV and had the following error:

AttributeError: 'Namespace' object has no attribute 'merge_del_threshold'

Thanks!

**Comment by tjiangHIT** [comment]
Hello woodoo46,
Thanks for letting me know this error.
In the current version of cuteSV (1.0.5), I added several new options like _merge_del_threshold_ , which is a key parameter to define the signatures of deletion to merge. I retest cuteSV-1.0.5 but didn't raise this error. Hope you provide more details like which line in which script raising the error.
Thank you.
Tao

**Comment by woodoo46** [comment]
I downloaded the released zip file, installed it, and ran it, then I got the error.

**Comment by tjiangHIT** [comment]
Hello @woodoo46 ,

Sorry for hearing this depressing thing.
I download the [cuteSV-v1.0.5 source code](https://github.com/tjiangHIT/cuteSV/archive/cuteSV-v1.0.5.zip) and install it with _python setup.py install_, but no error bothers me. 
Recently, I am busy improving the performance of cuteSV, maybe my  temporary change at some time caused this error. Please download the latest version of cuteSV via https://github.com/tjiangHIT/cuteSV/archive/master.zip.
Hope this can help you.

Soon afterward, I will release cuteSV1.0.6, which fixes a several bugs and brings more useful new options.

Best
Tao

**Comment by woodoo46** [comment]
OK. Thanks. I switched back to 1.0.4, it works fine. For now, I will just stick with 1.0.4.

**Comment by tjiangHIT** [comment]
Hello woodoo46,
I have released cuteSV v1.0.6, please use the latest version.
Thanks for using cuteSV and hope you give more feedbacks or suggestions.
Now I will close this issue.
If you have any questions, feel free to open it again,
Best
Tao
