### ISSUE TITLE
ValueError: mapping information not recorded in index or index not available

### ISSUE THREAD

**Issue by Nurbanu-Erolmez** [tjiangHIT/cuteSV#30]
Hi,

I will be using cuteSV to detect the variations but I cannot properly run the codes, getting "ValueError: mapping information not recorded in index or index not available" or "[E::idx_find_and_load] Could not retrieve index file for 'input.bam'"

Thanks,
Nurbanu

**Comment by tjiangHIT** [comment]
Hello @Nurbanu-Erolmez ,

Please confirm your bam file has been sorted and indexed with samtools.
If not, please use the commands shown below:
```sh
samtools view -bS your.sam | samtools sort -O bam -T ./ - -o your.bam
samtools index your.bam
```
Hope this helps.
Best,
Tao

**Comment by tjiangHIT** [comment]
Hello @Nurbanu-Erolmez ，

This error indicates your bam file has no read alignments.
Please check your original fasta/fastq file format, and I will be happy if you can share your running commands for each step.

Best,
Tao

**Comment by Nurbanu-Erolmez** [comment]
Thanks for replying and guide. I checked my fasta and bam files again and realized that the bam.bai file was missing. 
Then I created again. Now cuteSV is working.

Thanks a lot,
Nurbanu
