### ISSUE TITLE
No INS in the results

### ISSUE THREAD

**Issue by quentin0515** [tjiangHIT/cuteSV#35]
Hi!

I ran cuteSV on pacbio CLR data with following command:
cuteSV --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 200 --diff_ratio_merging_DEL 0.5 reads.bam hg38.no_alts.fasta output.vcf ./output
And I got DEL, DUP, INV, BND in the output, but no INS.
Is this normal for a cuteSV output? Do you have ideas about why this is happening?
Thanks!

**Comment by Meltpinkg** [comment]
It is not normal for cuteSV to output like this. We would like you to provide the _reads.bam_ for us to perform further debugging.
Thanks!

**Comment by tjiangHIT** [comment]
Hello @quentin0515,

I have updated cuteSV.
Please have a new trial.

Tao
