### ISSUE TITLE
question about INFO

### ISSUE THREAD

**Issue by huangyuanf** [tjiangHIT/cuteSV#39]
hello:
 when i run cutesv on ngmlr.sort.bam , INFO of all out which including BND is IMPRECISE;SVTYPE=BND;RE=1;RNAMES=NULL 
IMPRECISE represent Imprecise structural variant,what is wrong? And there is no CHR2 and END?

**Comment by huangyuanf** [comment]
I used cuteSV-v1.0.10;how can i get CHR2 and END

**Comment by tjiangHIT** [comment]
Hello @huangyuanf,

Thanks for using cuteSV.
**_IMPRECISE_** just indicates an imprecise structural variant.
And you can manually resolve CHR2 and END from the info list in ALT filed.
Hope this helps.

Best,
Tao
