### ISSUE TITLE
Increasing sensitivity of SV calling 

### ISSUE THREAD

**Issue by zhemingfan** [tjiangHIT/cuteSV#44]
As noted in [Issue 42](https://github.com/tjiangHIT/cuteSV/issues/42), I'm also having some issue detecting some known tandem duplication and deletion calls -  I was wondering what parameters of cuteSV we could use to optimize sensitivity. 

Thanks,
Jeremy

**Comment by tjiangHIT** [comment]
Hello @zhemingfan,

Thanks for your question.
Could you tell me there are enough supporting reads (over the value of **_--min_support_**) that standing by the SV?
You can have a look at the region of the breakpoint from **_.sigs_** files.
I guess you can decrease the value of **_--min_support_** and enable cuteSV to report these SVs without enough supporting reads.
Hope this can help you.

Best,
Tao

**Comment by zhemingfan** [comment]
Thanks Tao, 

I was wondering if it would be also possible to increase the --max_size parameter to infinity (i.e -1)?

**Comment by tjiangHIT** [comment]
Hello @zhemingfan，

We have updated cuteSV and enable it to detect full-length SVs when applying --max_size -1.
Please git clone the latest version and try again.

Best, 
Tao

**Comment by zhemingfan** [comment]
Thanks @tjiangHIT for the update, I've been setting it as an arbitrarily high number recently - I'm not sure if this is a problem on my end but the new version is returning an error:

`ValueError: file does not contain alignment data` when using the Github installation. 

The old version I got from conda worked fine.

**Comment by zhemingfan** [comment]
Works great, thanks!
