### ISSUE TITLE
Feature Request -  Allele Frequency Output 

### ISSUE THREAD

**Issue by zhemingfan** [tjiangHIT/cuteSV#48]
Hi @tjiangHIT ,

I was wondering if there could be an option to output allele frequency `##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency."> ` that other SV callers like Sniffles output.

**Comment by tjiangHIT** [comment]
Hello @zhemingfan，

Thanks for your suggestion, we have added allele frequency output when applying genotype. Please git clone the new codes for your test. Hope this can help you.

Best,
Tao

**Comment by zhemingfan** [comment]
Working now - thank you!
