### ISSUE TITLE
Unable genotype

### ISSUE THREAD

**Issue by zhqduan** [tjiangHIT/cuteSV#5]
Hi @tjiangHIT,

I used cuteSV (version 1.0.6) with a human PacBio data (both ngmlr and pbmm2 aligner) according to the command:

`cuteSV -t 16 -l 50 --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.2 --diff_ratio_filtering_INS 0.6 --diff_ratio_filtering_DEL 0.7 $bam_file $sample.vcf $sample`

However, I got the vcf result that all the genotype of detected SV is "./.". It seems cuteSV couldn't measure the DR (High-quality reference reads) information. Do you have any suggestion for solving this problem? Thank you!

```
-  #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NULL
- 1       10338   cuteSV.DEL.0    N       <DEL>   .       PASS    PRECISE;SVTYPE=DEL;SVLEN=-76;END=10414;CIPOS=-19,19;CILEN=-6,6;RE=16;STRAND=+-  GT:DR:DV:PL:GQ  ./.:.:16:.,.,.:.
- 1       10402   cuteSV.INS.0    N       <INS>   .       PASS    PRECISE;SVTYPE=INS;SVLEN=58;END=10403;CIPOS=-4,4;CILEN=-2,2;RE=16       GT:DR:DV:PL:GQ  ./.:.:16:.,.,.:.
- 1       10818   cuteSV.INS.1    N       <INS>   .       PASS    PRECISE;SVTYPE=INS;SVLEN=100;END=10819;CIPOS=-21,21;CILEN=-7,7;RE=98    GT:DR:DV:PL:GQ  ./.:.:98:.,.,.:.
- 1       136960  cuteSV.INS.2    N       <INS>   .       PASS    PRECISE;SVTYPE=INS;SVLEN=280;END=136961;CIPOS=-22,22;CILEN=-11,11;RE=20 GT:DR:DV:PL:GQ  ./.:.:20:.,.,.:.
- 1       227418  cuteSV.BND.0    N       ]2:243159580]N  .       PASS    PRECISE;SVTYPE=BND;CHR2=2;END=243159580;RE=9    GT:DR:DV:PL:GQ  ./.:.:9:.,.,.:.
- 1       227421  cuteSV.BND.1    N       [5:180900319[N  .       PASS    PRECISE;SVTYPE=BND;CHR2=5;END=180900319;RE=11   GT:DR:DV:PL:GQ  ./.:.:11:.,.,.:.
- ...
```

**Comment by tjiangHIT** [comment]
Hi @zhqduan ,

Thank you for using cuteSV.
In terms of your question, please use **_--genotype_** in your command in order to enable cuteSV to perform genotyping.

Best,

Tao

**Comment by zhqduan** [comment]
Hi Tao,

Thanks for your prompt reply.
I have tested my data with the parameter "--genotype". However, it is not work and the result vcf file has not the variant records, namely, there are only header (## and #) in the vcf file.
I guess cuteSV needs specialized bam file. 

Best,

Zhongqu

**Comment by tjiangHIT** [comment]
Hi @zhqduan ，

cuteSV uses general sorted BAM with index file (i.e. .bai) as input. I guess that some older files caused the error. Please make a new clean folder, and rerun cuteSV in this folder with **_-t 16 -l 50 --genotype  --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.2 --diff_ratio_filtering_INS 0.6 --diff_ratio_filtering_DEL 0.7 $bam_file $sample.vcf $sample_** .

Best,

Tao

**Comment by zhqduan** [comment]
Hi Tao,

It still not work according to your suggestion.

**Comment by tjiangHIT** [comment]
Hi @zhqduan ,

Sorry for the late reply.
Could you please supply a part of your data for me to check the error?
You can use these commands to extract data as below:
**_samtools view -H BAM > check.sam
samtools view BAM 1:10000-110000 >> check.sam
samtools view -buS check.sam | samtools sort -O bam -T . - > check.bam
samtools index check.bam_**
Please send  **_check.bam_** and  **_check.bam.bai_** to me via tjiang@hit.edu.cn.

Best,

Tao

**Comment by tjiangHIT** [comment]
Finally, this error is raised by python version.
Please use python3 to install cuteSV.

**Comment by Akazhiel** [comment]
Regarding this issue, I've run the latest version of cuteSV with the `--genotype` flag and with `Python 3.7` and I still got quite some variants with a `.` in the `QUAL` field and only reported the `DV`. There was no genotype or DR info to be found in any of these variants.

**Comment by Meltpinkg** [comment]
Hello, @Akazhiel

**Comment by Meltpinkg** [comment]
Helllo, @Akazhiel 

When running cuteSV with --genotype, there are also some specific circumstances which would lead to no genotype or DR for variants. 
In cuteSV, the parameter `gt_round` controls the maximum round of iteration for alignments searching when performing genotyping. There are many repeat regions in genome and these repeat regions may bring local high coverage reads. So it is time consuming to calculate genotype in these regions. Also, the accuracy of genotype is relatively low in repeat regions.
Considering all these factors, we output './.' for these variants directly.
Hope it will help!

Best,
shuqi

**Comment by Akazhiel** [comment]
Hello @Meltpinkg 

I understand these regions might be hard to genotype that's why you report them as `./.` and that's not a big issue for my use case but, the number of reads reported in the `DV` field is greatly overestimated, as if it was reporting all the reads in that region as variant reads, when upon checking manually on IGV there are really few reads supporting this variant. Could this perhaps be a bug in how the variant is reported?

Best regards,
Jonatan

**Comment by Meltpinkg** [comment]
Hello @Akazhiel 

cuteSV calculates `DV` by counting variant signatures which are extracted from the alignments. And I guess one probable reason may be that there are some signatures contained in the supplementary alignments which cannot be seen on IGV.
While it's just a conjectural reason and actually I can't make sure the definite reason for the overestimated DV. So could you please give me some examples with the alignments around the variants with wrong DV(part of the input bam)? It would be of great help for me to confirm this problem.
Thanks a lot!

Best,
Shuqi
