### ISSUE TITLE
the meaning of the output for eval_sim.py

### ISSUE THREAD

**Issue by azure-twilight** [tjiangHIT/cuteSV#54]
I want to use eval_sim.py to evaluate my simulated data, but I don't know the meaning for the output. How can I get precision, recall, F1-score?

**Comment by Meltpinkg** [comment]
Hello, @azure-twilight 

The output of eval_sim.py contains **TP** and **TN** from different SV type and different SV callers. And you can get the three indicators from the expressions below:
  **precision** = TP / call_cnt
  **recall** = TN / ref_cnt
  **F1** = 2 * precision * recall / (precision + recall)
where call_cnt means the number of SVs discovered by the caller, and ref_cnt means the number of SVs in the ground truth.

Best,
shuqi

**Comment by azure-twilight** [comment]
I see two columns in the output, does it mean that the first column is TP or TN and the second column is call_cnt or ref_cnt?
For example, in the output 
TP-1 of INS:     7304    8081
TN-1 of INS:     7450    9904
the precison is 7304/8081, the recall is 7450/9904?

By the way, what's the difference between TP-1 and TP-2?  Should I use TP-1+TP-2 to calculate the presicion or recall?

**Comment by Meltpinkg** [comment]
Hello, @azure-twilight 
In the benchmark result, the first column is TP or TN and the second column is call_cnt or ref_cnt. And just as you say, your calculation of precision and recall is correct.
TP-1/TP-2 represents evaluating SVs without/with genotyping, respectively.

Best,
shuqi
