### ISSUE TITLE
Nested deletion detection

### ISSUE THREAD

**Issue by HeleneKretzmer** [tjiangHIT/cuteSV#55]
Hi,
First of all thanks a lot for this super fast and performant tool.
I ran cuteSV on my ONT dataset with an average coverage of 30X. I know, that the sequenced cell line has a nested deletion. One allele has a large, about 30kb long deletion and the other allele shows a 15kb deletion- both end at the same location. The coverage profile looks like 30X, then for 15kb it is about 15X, then for another 15X there is no coverage, and then it is back to almost 30X.
When I run cuteSV, I get the large 30kb deletion reported, however, not split into hetero- and homozygous parts. Can you recommend any parameters to improve the sensitivity here? Is cuteSV in general able to detect such nexted events?
Thanks a lot!

**Comment by Meltpinkg** [comment]
Hi, @HeleneKretzmer 

Thanks for using cuteSV!
For the question you rasied, we simulated a dataset which contains two alleles where one allele has a deletion of 30k and the other allele has a deletion of 15k. Then we use pbsim2 to simulate the sequencing data of 30x totally and use the default parameter of minimap2 to achieve the alignment bam. Then we use cuteSV to apply SV calling. While the sequencing coverage is 30x, we use -s 5 in cuteSV and the other parameters are all default. The vcf file generated by cuteSV reported 2 SVs of 30k and 15k. The simulated bam and result of calling is shown below. So this simulation test shows cuteSV is able to detect nested deletion.
![image](https://user-images.githubusercontent.com/47966870/135046825-6c45667a-c6cd-41d8-922f-2687c6621f1f.png)
```
1       9999999 cuteSV.DEL.28   <DEL>   G       59.1    PASS    PRECISE;SVTYPE=DEL;SVLEN=-30000;END=10029999;CIPOS=-0,0;CILEN=-1,1;RE=11;RNAMES=NULL;AF=0.6111;STRAND=+-        GT:DR:DV:PL:GQ  0/1:7:11:59,0,21:20
1       10015001        cuteSV.DEL.29   <DEL>   A       85.9    PASS    PRECISE;SVTYPE=DEL;SVLEN=-14998;END=10029999;CIPOS=-0,0;CILEN=-2,2;RE=9;RNAMES=NULL;AF=1.0;STRAND=+-    GT:DR:DV:PL:GQ  1/1:0:9:86,23,0:22
```
By the way, we simulated the deletions as following and I'd like to confirm whether I have correctly comprehended it. The two nested deletions appear on different alleles and share the same ending position.
![image](https://user-images.githubusercontent.com/47966870/135048679-f3f7327d-36cd-4b11-a4de-23d2d39a11ea.png)

As our simulation test detected the nested deletions successfully, if it still doesn't work on your dataset, can you please provide part of your input data for us? We only need the bam file around the nested deletion. It will be of great help to handle this problem.
Hope it will help!

Best,
Shuqi

**Comment by Chenglin20170390** [comment]
@tjiangHIT Hi, JiangTao,   thanks for developing such usefull tool for SV detection,.

  I have a question about nested INV by Diploid assembly. Did cuteSV can detect nested INV base on Diploid assembly  genome?

**Comment by tjiangHIT** [comment]
Hello @Chenglin20170390,
Thanks for using cuteSV.
cuteSV is designed to call a single type of SV (i.e., DEL, INS, INV, DUP, BND) and not for a nested one.
But you can manually merge them in a local genomic region as a nested SV.

Best regards,
Tao

**Comment by Chenglin20170390** [comment]
thanks , that's very useful!

**Comment by Chenglin20170390** [comment]
thanks , that's very useful!
