### ISSUE TITLE
Any additional approach for population study? 

### ISSUE THREAD

**Issue by AJ211** [tjiangHIT/cuteSV#6]
Dear Tao,
    I want to check if there are special operations for the population study just like the joint-calling strategy of sniffles (https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population).

Thanks in advance
Jane

**Comment by tjiangHIT** [comment]
Hello @AJ211 
The original intention of the design of cuteSV is to discover SVs on the individual genome. So I do not develop force calling function to detect SVs from the cohort. I will add force calling option to my to-do list, and I think the combination of the future version of cuteSV and SURVIVOR will be able to achieve the population-based SV calling. 
Thanks again for pointing this out.

Tao

**Comment by tjiangHIT** [comment]
Hello @AJ211 
Sorry for replying this issue so late. 
Finally, cuteSV has the ability to perform force calling. Thanks to @Meltpinkg for her great work.
Let me give a short description for running cuteSV to complete population-based SV calling:
1. Run cuteSV for each sample to generate sample specific SV callsets.
2. Perform [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR) to merge every single vcf into **_merged.vcf_**.
3. Rerun cuteSV for each sample with **_-Ivcf merged.vcf_** (force calling step).
4. Perform [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR) again to merge every force called single vcf into **_final_merged.vcf_**.
Please git clone the latest codes and wish for hearing your feedbacks!

Best,
Tao
