### ISSUE TITLE
Breakpoint problem

### ISSUE THREAD

**Issue by bernicegu** [tjiangHIT/cuteSV#60]
HI 
Thanks for the software provided, but I have a question,.
what does the location of the resulting chromosome '[[',']]' represent when detecting BND,? 
what if I want to stitch the sequences at the left and right ends of the breakpoint together, if the negative chain of the reference genome is aligned

Look forward to your answer

**Comment by bernicegu** [comment]
Thank you very much for your answer！
But  took a look at the sequence that detected the breakpoint, mapped to different chromosomes, and there will be gap in the middle,   What standard upon which this case is judged as a breakpoint?

**Comment by tjiangHIT** [comment]
Hello @bernicegu,

For a read having split alignments (described by its primary and supplementary alignments), cuteSV records each split by a 6-tuple Seg = (Reads, Reade, Refs, Refe, Chr, Strand) (also termed as a “segment”), where Reads, Reade, Refs, Refe respectively indicate the starting and end coordinates on the read and the reference genome, and Chr and Strand respectively indicates its chromosome and orientation. If two adjacent segments are mapped to different chromosomes and the two segments are < 100 bp distant on the reads, cuteSV composes a translocation signature:
> Sig = (Chr1, Ref1e, Chr2, Ref2s, ReadID), if Chr1<Chr2 and ++
> Sig = (Chr2, Ref2s, Chr1, Ref1e, ReadID), if Chr2<Chr1 and ++
> Sig = (Chr1, Ref1e, Chr2, Ref2e, ReadID), if Chr1<Chr2 and +-
> Sig = (Chr2, Ref2e, Chr1, Ref1e, ReadID), if Chr2<Chr1 and +-
> Sig = (Chr1, Ref1s, Chr2, Ref2s, ReadID), if Chr1<Chr2 and -+
> Sig = (Chr2, Ref2s, Chr1, Ref1s, ReadID), if Chr2<Chr1 and -+
> Sig = (Chr1, Ref1s, Chr2, Ref2e, ReadID), if Chr1<Chr2 and --
> Sig = (Chr2, Ref2e, Chr1, Ref1s, ReadID), if Chr2<Chr1 and --

where < means the first chromosome is alphabetically smaller than the second chromosome and “++”, “+−”, “−+”, “--” indicate the combination of strands for an inter-chromosomal SV.

Best,
Tao

**Comment by bernicegu** [comment]
@tjiangHIT
How can I see this6-tuple Seg？ The result is not output . And I see that two segments(cuteSV composes a translocation signature) middle distance in the bam file  are > 100 bp

**Comment by Meltpinkg** [comment]
Hello @bernicegu 

cuteSV extracts the SV signatures from the 6-tuple Seg, and the SV signatures are written in the temporary files named 'TRA.sigs' located in the work directory assigned in the running command. You can add the parameter '--retain_work_dir' to retain this file. The SV results that cuteSV outputs are produced by these tuple Segs.
Hope it will help.

Best,
shuqi
