### ISSUE TITLE
cuteSV call SV with length =0 from haplotype-resolved assemblies

### ISSUE THREAD

**Issue by zhqduan** [tjiangHIT/cuteSV#64]
Hello,

When I use cuteSV to call SVs from haplotype-resolved assemblies, a strange SV was called, with the length equal to 0, and no Ref seqs are available:
chr1_KI270709v1_random	1	cuteSV.DEL.6890		G	11.8	PASS	SVTYPE=DEL;SVLEN=0;END=1;RE=1;RNAMES=	GT	0/1
Any idea with this case? Thank you very much!

**Comment by tjiangHIT** [comment]
Hello @zhqduan,

Thank you for selecting cuteSV for your project.
I apologize for this error.
Based on my current experience, I have not enough idea about it.
I will be appreciated it if you can share the sub-data for this call for me to reproduce this error and fix it.

Thanks!
Tao

**Comment by zhqduan** [comment]
Hi @tjiangHIT,

Thanks for your reply. The haplotype-resolved assemblies are [hap1](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/018/472/595/GCA_018472595.1_HG00438.alt.pat.f1_v2/GCA_018472595.1_HG00438.alt.pat.f1_v2_genomic.fna.gz) and [hap2](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/018/471/515/GCA_018471515.1_HG00438.pri.mat.f1_v2/GCA_018471515.1_HG00438.pri.mat.f1_v2_genomic.fna.gz), the reference is hg38.no_alt.fa and the cuteSV commands are:

> cat <(zcat $fna_file1 |sed 's/>/>cutesvh1_/g') <(zcat $fna_file2 |sed 's/>/>cutesvh2_/g')|gzip >sample.fasta.gz
> minimap2 --paf-no-hit -a -x asm5 --cs -r2k -t 16 reference sample.fasta.gz > sample.sam;
> samtools sort -m1G -@16 -o sample.sorted.bam sample.sam;
> samtools index -@16 sample.sorted.bam;
> mkdir sample
> cuteSV sample.sorted.bam reference sample.hic.vcf sample -s 1 -t 16 --genotype --report_readid -p -1 -mi 500 -md 500 --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5
> python ~/cuteSV/diploid_calling.py sample.hic.vcf sample.final.vcf

Thanks.
Zhongqu

**Comment by tjiangHIT** [comment]
Hello @zhqduan,

Sorry for replying so late.
Due to the absence of a judgment of the initialization condition for SV signature, the initialized signatures are involved by cuteSV mistakenly. Now we have repaired this error. Please git clone the latest codes and check it.
Thank you again for pointing this out and waiting patiently.

Best wishes,
Tao

**Comment by zhqduan** [comment]
Thank you very much for your answer.
