### ISSUE TITLE
Allele not matching the reference sequence

### ISSUE THREAD

**Issue by RenzoTale88** [tjiangHIT/cuteSV#65]
Hello,
I'm currently processing the variants called using HiFi sequences. I've got both short variants called using either DeepVariant or Clair and structural variants called using cuteSV. After calling the variants, I've combined the data using bcftools. However, since there is a level of overlap between the variants called by the short read caller and the SV caller (especially in the range 30-50bp) I'm trying to simplify the dataset using `bcftools norm`.
However, when I run the command as follow, I get the following error:
```
bcftools norm -f ref.fa tmp.vcf > tmp2.vcf
Reference allele mismatch at 000001F:745885 .. REF_SEQ:'T' vs VCF:'A'
```
I've seen the issue #43 and I understand the trouble in defining the actual breakpoint, especially with ambiguous positionings. However, I think it would be good to have the software to print out the allele matching the base, so that there is consistency and the VCF can be used in downstream analyses without having to apply custom fixing. Would it be possible to patch this issue?

Alternatively, does this issue affect only insertions? If so, is it always that the nucleotide refers to `POS-1`?
Thank you in advance,
Andrea

**Comment by tjiangHIT** [comment]
Hello @RenzoTale88,

Thank you for pointing this out!
This will improve the facility of cuteSV for downstream analyses.
I will deal with this issue in the next few days and remind you when updating the source code.

Best,
Tao

**Comment by bnoyvert** [comment]
Yes, it seems that all the coordinates in the vcf output are shifted by 1, so they are 1 more than they should be for the reference allele to match the reference fasta file.

**Comment by tjiangHIT** [comment]
Hello @RenzoTale88 and @bnoyvert,

Thanks again for reporting this bug.
Now we have adjusted the way of the computation of the reference allele, please git clone the latest codes and check it.

Best regards,
Tao

**Comment by RenzoTale88** [comment]
@tjiangHIT thank you for this! Just out of curiosity, did you also updated the anaconda relase? Or do we need to specifically install it by cloning from github?

**Comment by tjiangHIT** [comment]
Hi @RenzoTale88,

Currently, please git clone the latest codes and install cuteSV.
We still improve or repair the function according to the known issue.
After that, we will push a new version on anaconda and PyPI.
Thank you again for your contribution.

Best regards,
Tao

**Comment by bnoyvert** [comment]
Hi @tjiangHIT ,

Many thanks for looking into the issue.

I am sorry, I think the variant calls are still wrong. Running the updated version of cuteSV I can see that the update affects insertions only, but deletions are still called the same way as before. So the deletion reference allele doesn't match the reference sequence.

Also I believe the variant coordinate is still wrong even in the case of insertions. I generated a simple example:
![insertion](https://user-images.githubusercontent.com/97630376/149999376-38879781-9016-44d8-86ec-3136b5e30f78.png)
There is a same 32 base insertion in all the reads, so clearly it should be called as:
`2	169724251	cuteSV.INS.0	C	CCTGAGTGACCTATAAAGAGACTTAGACTCCCA`
The previous version of cuteSV calls it as
`2	169724253	cuteSV.INS.0	C	CCTGAGTGACCTATAAAGAGACTTAGACTCCCA`
with the wrong reference base at 2:169724253, and the latest version calls it as
`2	169724253	cuteSV.INS.0	A	ACTGAGTGACCTATAAAGAGACTTAGACTCCCA`
now with the right reference base, but the alternative allele is still wrong. And I don't think this is an alternative presentation of the same variant.

The bam and the vcf are attached.
The command used:
`cuteSV insertion.bam human_g1k_v37.fasta insertion.vcf ./ --genotype`

Thank you,
Boris

[insertion.zip](https://github.com/tjiangHIT/cuteSV/files/7891636/insertion.zip)

**Comment by tjiangHIT** [comment]
Hello @bnoyvert and @RenzoTale88,

It's me again.
A new modification of position has been updated, please check it.
Hope your feedback. 

Best,
Tao

**Comment by bnoyvert** [comment]
Thank you @tjiangHIT,

I think the reference alleles are matching the reference sequence now, thank you for fixing it.

Best wishes,
Boris

**Comment by tjiangHIT** [comment]
Hello @bnoyvert,

Thank you for your kindly reply.
All updates have been synced to the Bioconda and PyPi.

Best,
Tao
