### ISSUE TITLE
query regarding QUAL

### ISSUE THREAD

**Issue by prasundutta87** [tjiangHIT/cuteSV#67]
Hi,

I was just wondering if the variant quality (QUAL) in VCF is phred scaled. Its definition is absent in the vcf metadata (cuteSV-1.0.10). I am assuming it is, but just confirming. I observed that in the paper, variants were removed which had variant quality less than 5. Is it QUAL you are referring to? 

Regards,
Prasun

**Comment by tjiangHIT** [comment]
Hello @prasundutta87,

The variant quality (QUAL) for each SV that cuteSV reports is phred scaled (-10log10).
The QUAL of an SV is less than 5 will be marked as q5 and recommended to filter out.

Best,
Tao

**Comment by prasundutta87** [comment]
Thank you so much for this reply. I will close this issue now.
