### ISSUE TITLE
supporting reads?

### ISSUE THREAD

**Issue by proinde** [tjiangHIT/cuteSV#7]
I'm currently trying to replace sniffles in a workflow with cuteSV. One of the more useful features for complex SV confirmation is that sniffles outputs the read_names for the reads that support each SV in the INFO.RNAMES field. Might I request this as a feature?

**Comment by tjiangHIT** [comment]
Hello @proinde 

Thank you for pointing this out.
As your request, I have added the INFO.RNAMES field, add each SV call owns a supporting read name list. Please confirm.
Welcome to propose more suggestions to improve cuteSV more powerful.

Thanks
Tao
