### ISSUE TITLE
Multi-sample / joint calling Recommendations?

### ISSUE THREAD

**Issue by bbimber** [tjiangHIT/cuteSV#77]
Hello,

We generated PacBio CLR data on a small cohort that includes several trios. From my understanding, cuteSV is run per-sample. Do you have recommendations on tools or processing steps to unify SVs calls across multiple samples? As you probably know, many SV callers have joint-calling modes. My current plan to is to simply merge them using GATK or similar and work with this file.

Thanks.

**Comment by tjiangHIT** [comment]
Hello @bbimber,

Thanks for using cuteSV.
Let me give a short description for running cuteSV to complete population-based SV calling:
1. Run cuteSV for each sample to generate sample specific SV callsets.
2. Perform [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR) to merge every single vcf into **_merged.vcf_**.
3. Rerun cuteSV for each sample with **_-Ivcf merged.vcf_** (force calling step).
4. Perform [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR) again to merge every force called single vcf into **_final_merged.vcf_**.

Best regards,
Tao

**Comment by Meltpinkg** [comment]
Hello, @bbimber 
The second command should repeat these arguments as you wrote above.
Hope it will help!

Best,
Shuqi

**Comment by bbimber** [comment]
ok, thank you
