### ISSUE TITLE
Any suggestion about Genotyping using short-reads

### ISSUE THREAD

**Issue by biozzq** [tjiangHIT/cuteSV#8]
Dear @tjiangHIT 

Thank you for your good tools, I will have a try. I will use several representative long-read samples to generate the candidate SVs, and then genotype these SVs in short-reads samples. Do you have some suggestions about the tools used in genotyping? I have tried to use paragraph (https://github.com/Illumina/paragraph) but failed to prepare the input file.

Thanks
Zheng Zhuqing

**Comment by tjiangHIT** [comment]
Hellp @biozzq 

Thank you for using cuteSV. Although the performance of the generation of genotypes in cuteSV is better than the state-of-the-art long-reads alignment based methods in my evaluations, it is promising to run genotyping with short-reads. I have read the README.md of paragraph and find that the format of cuteSV's callsets is not satisfied with the input requirements of paragraph (such as, cuteSV cannot produce INFO.SEQ in the current version). 
I will improve the output info as soon as possible to enable cuteSV support more tools. And welcome to point any suggestions to make it more powerful and practical.

Thank you
Tao

**Comment by tjiangHIT** [comment]
Hello @biozzq 
Sorry for the delay. I update cuteSV and can output inserted sequence in ALT field. Please check it.
If you have strong demand for put allele sequence into INFO field, please tell me.
Now I will closed this issue. If you have any questions please reopen it.

Best,
Tao
