### ISSUE TITLE
Reading material or step by step procedure for force calling of trio (family) analysis

### ISSUE THREAD

**Issue by prasundutta87** [tjiangHIT/cuteSV#81]
Hi,

I am planning to use the force calling feature to mimic joint genotyping in cuteSV as I am working with trios. However, I haven't been able to find any reading material on the general algorithm or a simple explaination on how to run force calling and what actually is happening in force calling. Can I be kindly be pointed to a resource where I can find this information? 

Regards,
Prasun

**Comment by Meltpinkg** [comment]
Hi, @prasundutta87 

The joint genotyping in cuteSV aims at genotyping each individual on the variation of population trio. It can be applied through the following 4 steps. Let's suppose that there are 3 people in this trio containing father, mother and child (more is also practicable).

1. perform SV calling by cuteSV to generate three individual VCFs
2. use SV merging tools such as Truvari, Jasmine or SURVIVOR to merge three inidividual VCFs into a trio VCF, which named **merged.vcf**
3. perform force calling by cuteSV on each individual to re-genotype the sample. With given **-Ivcf merged.vcf** as input, cuteSV will genotype each individual on all variations in the trio VCF. The command of force calling is like:
 `cuteSV {individual.bam} {reference.fasta} {individual.fc.vcf} {work directory} -Ivcf merged.vcf [options]`
4. use bcftools or merging tools in step 2 to merge force called individual VCFs into **trio.vcf**

After these steps, we will get the trio VCF containing all samples in the trio.

Best,
Shuqi

**Comment by prasundutta87** [comment]
Thank you so much, @Meltpinkg. Is there a plan to publish the force calling method or is it going to be published in a separate paper in the future? Just wanted to know if the concept in similar to the GVCF calling in the GATK SNP calling pipeline? Also, if further variant quality or genotype quality based filtering is required after the last merging step? I believe that the QUAL (variant quality) and GQ (genotype quality) values will get updated after the 3rd step mentioned above.

Regards,
Prasun

**Comment by Meltpinkg** [comment]
It's a great idea about force calling. And in my opinion, the concept of force calling method is similar to that in GATK.
After force calling, the QUAL and GQ will get updated, so it is necessary to apply filtering after the last merging step. For SV calling in single sample, the filter mostly based on the quality of genotype, while for SV calling in population group, the filter more depends on the HWE or missing rate of SVs.

For the second question, though the IMPRECISE SVs are filtered in the first step, the SVs conserved in other samples may lead to the SV point in population VCF. So it will be also genotyped in force calling step. To ge high quality variants, you can perform further SV filtering after force calling.

Best,
Shuqi

**Comment by prasundutta87** [comment]
Thanks @Meltpinkg ! I will filter SVs again after force calling to remove low QUAL and GQ and IMPRECISE variants before the final merging. 

After the final merging (step 4), I was hoping to go ahead to remove instances where there are mendellian violations as there are just 3 samples. Not sure if HWE and missing rate of SVs will be helpful in this case. Or, am I missing something here?

Regards,
Prasun

**Comment by Meltpinkg** [comment]
Hi @prasundutta87 !

Filtering through mendellian violations is effective in the trio group. However, HWE and missing rate is suitable for benchmarking SVs in large population group, not for small trio group. As there are just 3 samples, maybe it is not appropriate to use HWE or missing rate of SVs in this condition.

Best,
Shuqi

**Comment by prasundutta87** [comment]
Thank you so much @Meltpinkg for your help! :-)
