### ISSUE TITLE
query about IMPRECISE and PRECISE SVs

### ISSUE THREAD

**Issue by prasundutta87** [tjiangHIT/cuteSV#82]
Hi,

From [src/cuteSV/cuteSV_genotype.py](https://github.com/tjiangHIT/cuteSV/blob/e41bde358364b5724058c089bb5bc8a0ad9b75f2/src/cuteSV/cuteSV_genotype.py), I understood that SVs with homozygous reference genotype are marked as "IMPRECISE". Is it the only case or there is some other explaination of a SV being PRECISE or IMPRECISE in cuteSV? Or SVs are also marked IMPRECISE if breakpoints are unresolved?

Regards,
Prasun

**Comment by Meltpinkg** [comment]
Hello, @prasundutta87 

If the genotype of SV reported by cuteSV seems to be "0/0", it means that there are not enough reads supporting this SV. So in this case, cuteSV reports this SV as "IMPRECISE" due to the lack of the supporting reads evidence. In other words, the PRECISE or IMPRECISE depends on the count propotion of the supporting reads.
Hope it will help.

Best,
Shuqi

**Comment by prasundutta87** [comment]
@Meltpinkg, thanks so much for this explaination! It seems that the definition of PRECISE and IMPRECISE is different for different SV callers. I remove IMPRECISE variants before benchmarking any variant caller/aligner combination. I do this mostly because for a SV to be PRECISE or IMPRECISE technically depends on the aligner.  I hope it is the right thing to remove them before benchmarking. Once I choose an aligner and SV caller combination, I anyway filter off IMPRECISE SVs from cuteSV/sniffles and do not plan to use it for any downstream analysis. Can IMPRECISE variants be useful in some cases?

**Comment by tjiangHIT** [comment]
Hello @prasundutta87,

To obtain high-quality variants for generic downstream analysis, it is strongly recommended to remove the records marked as IMPRCISE and/or other associated tags. However, it is not a good idea if you want to apply some variants, which are located in complex regions and hardly detected in high confidence, in specific studies. You can try to retain all variants and filter them before the analysis.

Best regards,
Tao

**Comment by prasundutta87** [comment]
Thanks a lot @tjiangHIT . Its reassuring to hear that. As per many published benchmarking studies, I only retain precise SVs, keep only INS and DEL and convert DUP to INS as well before comparing it to the GIAB v0.6 Tier 1 high quality SV set.

As I am doing family based studies trio, in the beginning, I am only looking for the precise elementary SVs (5 types which most SV callers give). However, I will also look into IMPRECISE ones if I do not get any proper results. Thanks for the suggestion.

Regards,
Prasun
