### ISSUE TITLE
Start position going beyond chromosome v1.0.12

### ISSUE THREAD

**Issue by zhemingfan** [tjiangHIT/cuteSV#83]
Hi @tjiangHIT ,

I've been testting cuteSV version [v1.0.12](https://github.com/tjiangHIT/cuteSV/releases/tag/cuteSV-v1.0.12) with the CHM13-T2T genome, I noticed that cuteSV was calling a BND SV at chr15, position 99753196, but the chromosome only extends to position 99753195. I'm wondering whether this was fixed in the latest release?

**Comment by tjiangHIT** [comment]
Hello @zhemingfan,

We have fixed the breakpoint bug and adjusted it as it should be.
Please git clone the latest codes and install it.

Regards,
Tao

**Comment by zhemingfan** [comment]
Just tried it again. Resolved now. Thank you!
