### ISSUE TITLE
Using read terminal ends for SV calling - Targeted sequencing

### ISSUE THREAD

**Issue by ViriatoII** [tjiangHIT/cuteSV#85]
Hi,

do you have a parameter recommendation for using the terminal ends of reads to call SVs as well? 

This comes in the context of targeted sequencing, I have regions that are only covered by terminal ends of reads. I'm noticing that on those regions, even if the reads are different from the reference, an SV is not called, it's probably discarded due to the assumption of low quality in read ends.

Should I change the --max_cluster_bias_INS/DEL parameters? I'm using the default --min_support 10 and I definately have more than 10 reads with terminal ends reaching this location of interest.

Cheers,
Ricardo

**Comment by tjiangHIT** [comment]
Hello @ViriatoII,

Do you mean that there are a lot of low-mapping-quality reads in the region of interest?
If so, you can adjust the parameter of --min_mapq, which indicates that the minimum mapping quality value of alignment is to be taken into account, to a lower value.
Besides, if you are not sure there are enough reads in a local reads cluster, please also decrease the value of --min_support.

I hope this can help you.

Best regards,
Tao

**Comment by ViriatoII** [comment]
Thank you for the swift reply. I have many reads mapping with high quality (MAPQ 60), but my reads come from a different genotype than the reference genome, so SVs are expected.

I will make a toy example below with only 4 reads, but I have in fact up to 100 reads, of which maybe 20-30 reach a toy SV2 that is not called, while the toy SV1 is called.

Ref: #############################################
Read1: #####SV1#############
Read2: #####SV1###############
Read3: #####SV1################SV2##
ReadX: #####SV1################SV2###
Read30: ####SV1################SV2#########

**Comment by tjiangHIT** [comment]
Hello @ViriatoII,

Do you mean that only SV1 is identified but SV2 is not?
Currently, 
1) cuteSV can merge SV1 and SV2 into one call if the distance between them is short than the parameter of  --merge_del_threshold or --merge_ins_threshold.
2) When the two SVs are not merged but grouped in one cluster, cuteSV will only report the one with a larger size.
3) If you really want to call them separately, please decrease the parameters of --max_cluster_bias_INS/DEL in order to leave the two SVs in two different clusters.

Best,
Tao

**Comment by ViriatoII** [comment]
Thank you, that's helpful! Ultimately the main problem had to do with read mapping, changing parameters there avoided this trimming of the edges and now cuteSV calls the SV2 as well as the SV1 (separately, yes).

谢谢你 !
Ricardo

**Comment by tjiangHIT** [comment]
That sounds great!
Thank you for selecting cuteSV in your research.

Cheers!
Tao
