### ISSUE TITLE
Help with genotyping/interpreting

### ISSUE THREAD

**Issue by shaze** [tjiangHIT/cuteSV#91]
I'd appreciate some help in interpreting the output of what I am getting. If I run cuteSV on a bam file that I've created using `pbmm2`

I run it thus

`cuteSV  --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9  --max_cluster_bias_DEL 1000  --diff_ratio_merging_DEL  0.5  XNV01.bam Homo_sapiens_assembly38.fasta XNV01-cute.vcf tempwork`

The output CNV 
 
```

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	XNV01
chr13	1102642	cuteSV.INS.761	T	TATCTGTGTCTCTATCTCTATCTCTATCTCTATCTCTATCTGTGTCTATTGATATATCTGTATATATCTATCTAAATCTCTATCTCTATCTCTATCTGTGCCTATTGATATATCTGTATATATCTATCTCTATCTCTATCTCTATCTCTATCTCTATCTGTGCCTATTGATATATCTGTA	.	PASS	PRECISE;SVTYPE=INS;SVLEN=179;END=1122642;CIPOS=-0,0;CILEN=-10,10;RE=12;RNAMES=NULL	GT:DR:DV:PL:GQ	./.:.:12:.,.,.:.
```

How do I interpret?

Also if I add `--genotype` I get an empty VCF file. 

Many thanks for your time

**Comment by shaze** [comment]
Hi Tao, thanks for the response.

The vcf file has all the headers -- just no calls. 

If I set  `retain_work_dir`  I get

```
 du -sh tempwork/*
22M     tempwork/DEL.sigs
2.2M    tempwork/DUP.sigs
112M    tempwork/INS.sigs
432K    tempwork/INV.sigs
144M    tempwork/signatures
3.6M    tempwork/TRA.sigs
```

The data is 10x PacBio HiFi -- not  high coverage but good quality and I've been able to get calls from other tools so I don't think it's the data

**Comment by shaze** [comment]
The signature directory above is full of bed files

**Comment by Meltpinkg** [comment]
Hello! @shaze
 
Thanks for reporting the question to us. Could you provide a part of your data if it is available for us to check this error?
For the output SV above, you can extract the reads around the SV breakpoint by the commands like
`samtools view {bam} -h -b -o check.bam chr13:1082642-1122642`
It will be of great help for us to look into the error. Please send the **check.bam** to me via sakura_qian@163.com
Thanks in advance.

Best,
Shuqi

**Comment by shaze** [comment]
@Meltpinkg 

Shuqi, apologies I tracked down the problem which was due to my failure to pay attention when installing. I had somehow managed to install cuteSV without installing pyvcf.

cuteSV appears to run without error but if you use the `--genotype` option it tries to import pyvcf and fails and dies silently. I ran cuteSV  through strace and picked up the problem

Once I installed pyvcf it worked fine 

So -- the problem was all on my side.  Thank you for taking the time to investigate  -- it helped me find my mistake.

I am just going to run through all our samples and if all is good will close the ticket tomorrow

Scott

**Comment by Meltpinkg** [comment]
Hello, Scott @shaze 

I'm glad to hear that! Looking forward to your good news.

Best,
Shuqi

**Comment by shaze** [comment]
Thank you for your prompt help -- I worked it out.

As an aside, the problem seemed to be the PyVCF does not install cleanly using Python 3.10 using pip3. I then tried to install manually and it seemed to be OK but then there was still a problem. PyVCF doesn't seem under active development so I am not sure what the long term prognosis is here.

**Comment by tjiangHIT** [comment]
Hello @shaze,

Many thanks for telling us about this situation.
We will try to resolve this in the next version.

Best regards,
Tao
