### ISSUE TITLE
No BND/TRA records in diploid assembly based cuteSV with -p -1

### ISSUE THREAD

**Issue by zhixue** [tjiangHIT/cuteSV#93]
Hi!

CuteSV is a very nice tool. I used it to detect SVs using nanopore reads one year ago. Now I know that cuteSV can also use assembly to detect SVs so I have a try.

My question is similar with https://github.com/tjiangHIT/cuteSV/issues/36. But I noticed `-p -1` has been added in 
 https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV (2022 Jan 15).

I ran both two assemblies datasets in this demo (wenger and garg) using cuteSV but found no records of BND/TRA.
```
 cat HG002_wenger_final.vcf | grep -v '#' | awk -F 'SVTYPE=' '{print $2}' | awk -F ';' '{print $1}' |sort |uniq -c
  16068 DEL
   1793 DUP
  20074 INS
    235 INV

 cat HG002_garg_final.vcf | grep -v '#' | awk -F 'SVTYPE=' '{print $2}' | awk -F ';' '{print $1}' |sort |uniq -c
  16071 DEL
   1306 DUP
  19911 INS
    182 INV
```
Maybe there are some BND/TRA records because logs show
```
2022-07-26 20:21:09,275 [INFO] Finished 3-4:TRA/BND.
2022-07-26 20:21:09,275 [INFO] Finished 3-5:TRA/BND.
2022-07-26 20:21:09,275 [INFO] Finished 3-6:TRA/BND.
2022-07-26 20:21:09,276 [INFO] Finished 3-7:TRA/BND.
2022-07-26 20:21:09,276 [INFO] Finished 3-8:TRA/BND.
2022-07-26 20:21:09,276 [INFO] Finished 3-9:TRA/BND.
```

I also ran several assemblies datasets in my plant project but found no records as well. However, other tools (e.g. svim-asm) have detected. 

So I'm confused.

**Comment by tjiangHIT** [comment]
Hello @zhixue,

Many thanks for your attention, and apologies for this question.
We are now checking this issue and will reply later.

Tao

**Comment by tjiangHIT** [comment]
Hello @zhixue,
 Sorry for replying so late.
Now we have fixed bugs that caused this error.
Please git clone the latest code, reinstall it and try again.

Best regards,
Tao

**Comment by zhixue** [comment]
Hi Tao,  
I tried the latest code version on several datasets and found some BND records in all of them. 

Thank you so much!
