### ISSUE TITLE
'pysam.calignmentfile.AlignmentFile' object has no attribute 'get_index_statistics'

### ISSUE THREAD

**Issue by linshengnan09** [tjiangHIT/cuteSV#94]
Hi,
when i run cuteSV, I got an error：
Traceback (most recent call last):
  File "/home/xinhongjia/miniconda3/bin/cuteSV", line 745, in <module>
    run(sys.argv[1:])
  File "/home/xinhongjia/miniconda3/bin/cuteSV", line 741, in run
    main_ctrl(args, argv)
  File "/home/xinhongjia/miniconda3/bin/cuteSV", line 568, in main_ctrl
    contig_num = len(samfile.get_index_statistics())
AttributeError: 'pysam.calignmentfile.AlignmentFile' object has no attribute 'get_index_statistics'
Is it a version problem of pysam? I installed cuteSV by conda.
Thanks.

**Comment by tjiangHIT** [comment]
Hello @linshengnan09,

Thanks for using cuteSV in your work!
For this issue, please try to install it via _git clone_ or _pip_ again.
We are now checking the reason that caused the crash of **pysam** when installation from _conda_.

If you have any questions please leave a message.

Best regards,
Tao

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！

**Comment by linshengnan09** [comment]
Hi, 
I had try to install it via git clone or pip again，but encountered the same error.
Thanks.

**Comment by Meltpinkg** [comment]
Hi, @linshengnan09 

I think the problem may caused by pysam in the environment. 
You can install a new conda environment like below, and then install cuteSV. It can avoid conflicts with others.
```
conda create -n cutesv_env python=3  
conda activate cutesv_env  
conda install -c bioconda cutesv
```

Best,
Shuqi

**Comment by linshengnan09** [comment]
Hi,
It worked.
Thanks.
