### ISSUE TITLE
process freezes 

### ISSUE THREAD

**Issue by maxineliu** [tjiangHIT/cuteSV#96]
My issue is very similar to [#79](https://github.com/tjiangHIT/cuteSV/issues/79#issue-1174838530).

It seems frozen last 10 hours. It is 13:32, Aug 3, 2022 now. The process stops at:
```
2022-08-03 02:17:49,923 [INFO] Finished NW_025334753.1-NW_025334769.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334753.1-NW_025334777.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334753.1-NW_025334778.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334755.1-NW_025334767.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334759.1-NW_025334762.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334759.1-NW_025334769.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334760.1-NW_025334761.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334762.1-NW_025334772.1:TRA/BND.
2022-08-03 02:17:49,923 [INFO] Finished NW_025334763.1-NW_025334772.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334765.1-NW_025334769.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334765.1-NW_025334779.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334766.1-NW_025334784.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334767.1-NW_025334774.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334767.1-NW_025334784.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334768.1-NW_025334779.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334768.1-NW_025334780.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334770.1-NW_025334779.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334772.1-NW_025334778.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334772.1-NW_025334783.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334772.1-NW_025334788.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334775.1-NW_025334780.1:TRA/BND.
2022-08-03 02:17:49,924 [INFO] Finished NW_025334775.1-NW_025334787.1:TRA/BND.
```

cutesv version: v1.0.13, threads 16, memory 16G
command:
```
cuteSV --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 200 --diff_ratio_merging_DEL 0.5 \
        -s 1 --genotype --report_readid -p -1 -mi 500 -md 500 -t 16 \
        /home/maxine91/projects/def-jfu/results/minimap2_bufo.dir/aln.sorted.cy201704.bam \
        /home/maxine91/projects/def-jfu/data/bufo_genome/GCF_014858855.1_ASM1485885v1_genomic.fa \
        cutesv.cy201704.vcf \
        ./
```
/home/maxine91/projects/def-jfu/results/minimap2_bufo.dir/aln.sorted.cy201704.bam 77G
/home/maxine91/projects/def-jfu/results/minimap2_bufo.dir/aln.sorted.cy201704.bam.csi 24M
/home/maxine91/projects/def-jfu/data/bufo_genome/GCF_014858855.1_ASM1485885v1_genomic.fa 4.3G

I don't want to delete any scaffolds/chromosomes from my data like [#77](https://github.com/tjiangHIT/cuteSV/issues/79#issuecomment-1074895294), what should I do to avoid the frozen?

Thanks,
Maxine

**Comment by Meltpinkg** [comment]
Hello, @maxineliu 

I'd like to first apologize for the problem. I see in your command there is the parameter '--genotype', and I think it may be caused by the low speed for cuteSV's genotyping module.
I have several concerns about the problem. You can try the following experiments.
If the program has not exited, you can check whether it is actually running by look at `top` and see is there any process named cuteSV.
Then, when the log has outputed `Clustering structural variants.`, it means the first module of cuteSV has finished and in the temporary directory (for your command, it is the current directory when running cuteSV), 5 temporary files (ended with suffix _.sigs_) was generated. You can take a look by the size of these files via `ls -lh *.sigs` and let me know it, too.
In addition, considering the low speed for genotyping, you can try the command without the parameter '--genotype', if it can finish calling successfully, it indicates that the problem is surely in the genotyping module.

Also, we have been conscious of the low speed of the genotyping module, and we will improve this module in the new version of cuteSV in the near future.

Please feel free to reply if you have any further idea. I hope it will help.

Best regards,
Shuqi

**Comment by maxineliu** [comment]
Hi Shuqi,

Thanks for your prompt response!

I ran 'top' to monitor the process last time. I assigned cutesv into 16 treads, and 'top' displayed about 14 cutesv records. However, the column '%mem' is only %0.2 for each record when the processes were entered into 'frozen status'.

The size of 5 temporary files from the last run is:
```
[maxine91@gra-login2 cutesv.dir]$ ls -lh *.sigs
-rw-r----- 1 maxine91 maxine91 764M Aug  3 02:08 DEL.sigs
-rw-r----- 1 maxine91 maxine91  68M Aug  3 02:06 DUP.sigs
-rw-r----- 1 maxine91 maxine91 6.7G Aug  3 02:16 INS.sigs
-rw-r----- 1 maxine91 maxine91  43M Aug  3 02:06 INV.sigs
-rw-r----- 1 maxine91 maxine91 574M Aug  3 02:08 TRA.sigs
```

I will run cuteSV again without '--genotype'.

Thank you again for the kind response and advice!

Maxine

**Comment by maxineliu** [comment]
I ran cuteSV without`--genotype`, it completed pretty fast -- only takes 1.6 hours. However, the number of Svs in output VCF is much bigger than that in sniffles' VCF, it's 12330201 vs 3036302 (cuteSV vs sniffles2). Is it because of disable `--genotype`?

**Comment by Meltpinkg** [comment]
Hello @maxineliu 

The parameter `--genotype` only affects whether cuteSV calculates the genotype of each SV, it won't affect the number of SVs reported.
I saw you set the parameter `-s 1`, which means cuteSV will regard every abnormal alignment as an SV and lead to an excess of SV. In cuteSV, we recommand to set this parameter as **1/6 sequencing coverage**.
Therefore, we can draw a conclusion that too many SVs cause the long time of genptyping which is shown as the freeze. You can update the parameter `-s` to about 1/6 sequencing coverage of the alignment file. It will decrease the running time. However, over 3 million SVs is also a large number, it still needs some time to finish that. You can remove `--genotype` if you don't need the information of genotype.

Best,
Shuqi

**Comment by maxineliu** [comment]
Hi Shuqi @Meltpinkg ,

It's an update on my progress. The command I used recently is:
```
cuteSV --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 200 --diff_ratio_merging_DEL 0.5 \
        --max_size -1 --min_size 35 --min_support 3 \
        --report_readid -p 3 -r 1000 -t 16 --genotype \
        aln.sorted.sample.bam \
        GCF_014858855.1_ASM1485885v1_genomic.fa \
        cutesv.sample.vcf \
        ./
```
It takes 19.6 hours with 16 threads and 16G RAM. 1.8 million SVs are detected.

Thanks for all you do. Looking forward to the new version.

Maxine

**Comment by Meltpinkg** [comment]
Hi Maxine

It's my pleasure. I'm glad to hear the success.
When the new version is released, I will mention that in this issue.

Best regards,
Shuqi

**Comment by Meltpinkg** [comment]
Hello @maxineliu 

For the event I mentioned ago, we now have updated a new version of cuteSV (v2.0.1), which apparently speeds up the genotype module of SV calling. I think it would be helpful in genotyping large amount of SVs as you mentioned above.

The new version can be achieved via **git clone** or **conda** or **pypi**. 
If there is any confusion with the new version, please feel free to contact us.

Best,
Shuqi
